server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # Server ko register nahi karna hai
    fetch-registry: false  # Server kisi doosre server se registry nahi le raha

  server:
    enable-self-preservation: true
    