spring:
  application:
    name: user-management-service

  datasource:
    url: jdbc:mysql://localhost:3306/management
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Possible values: none, validate, update, create, create-drop
    show-sql: true  # Shows SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # For MySQL 8

server:
  port: 8072    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
